project:
  type: website
  output-dir: docs

website:
  title: "learn-python"
  google-analytics: 
    tracking-id: "G-NH7HMX9RVC"
    storage: none
    anonymize-ip: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Getting started
      - href: schedule.qmd
        text: Schedule
      - href: additional_resources.qmd
        text: Additional resources
  page-footer: 
    left: 
      - text: Copyright 2026, Sarah Stueve
    center: 
      - text: CC BY 4.0 Deed
        href: https://creativecommons.org/licenses/by/4.0/
    right: 
      - icon: github
        href: https://github.com/sarahstueve

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    # toc: true



